//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAYCALC.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAYCALC.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Using the application, you can calculate the amount of salary, the amount of wages &quot;on hand&quot;, the amount of expenses of the enterprise on payment of wages..
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The calculator of salary in Ukraine.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer.
        /// </summary>
        internal static string AuthorApp {
            get {
                return ResourceManager.GetString("AuthorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Andrey Ovcharenko.
        /// </summary>
        internal static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Amount.
        /// </summary>
        internal static string entrSALARY {
            get {
                return ResourceManager.GetString("entrSALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tax on income of individuals, UAH.
        /// </summary>
        internal static string IncomeTAX {
            get {
                return ResourceManager.GetString("IncomeTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About the application.
        /// </summary>
        internal static string labAbout {
            get {
                return ResourceManager.GetString("labAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Salary with charges (enterprise costs), UAH.
        /// </summary>
        internal static string labCOMPANY {
            get {
                return ResourceManager.GetString("labCOMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The amount of salary gross, UAH.
        /// </summary>
        internal static string labGROSS {
            get {
                return ResourceManager.GetString("labGROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum USC, UAH.
        /// </summary>
        internal static string labMaxSSC {
            get {
                return ResourceManager.GetString("labMaxSSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum wage, UAH.
        /// </summary>
        internal static string labMinSALARY {
            get {
                return ResourceManager.GetString("labMinSALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum USC, UAH.
        /// </summary>
        internal static string labMinSSC {
            get {
                return ResourceManager.GetString("labMinSSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The amount of salary net, UAH.
        /// </summary>
        internal static string labNET {
            get {
                return ResourceManager.GetString("labNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rates to calculate.
        /// </summary>
        internal static string labOptions {
            get {
                return ResourceManager.GetString("labOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal income tax (PIT),%.
        /// </summary>
        internal static string labRateIncomeTAX {
            get {
                return ResourceManager.GetString("labRateIncomeTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The rate of military duty,%.
        /// </summary>
        internal static string labRateMilitaryTAX {
            get {
                return ResourceManager.GetString("labRateMilitaryTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The rate of the unified social contribution (USC), UAH..
        /// </summary>
        internal static string labRateSSC {
            get {
                return ResourceManager.GetString("labRateSSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount to calculate, UAH.
        /// </summary>
        internal static string labSALARY {
            get {
                return ResourceManager.GetString("labSALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total taxes and fees, UAH..
        /// </summary>
        internal static string labTotalTax {
            get {
                return ResourceManager.GetString("labTotalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на expenses of the company.
        /// </summary>
        internal static string labTypeCOMPANY {
            get {
                return ResourceManager.GetString("labTypeCOMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gross.
        /// </summary>
        internal static string labTypeGROSS {
            get {
                return ResourceManager.GetString("labTypeGROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на net.
        /// </summary>
        internal static string labTypeNET {
            get {
                return ResourceManager.GetString("labTypeNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string labVersion {
            get {
                return ResourceManager.GetString("labVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string LanguageEng {
            get {
                return ResourceManager.GetString("LanguageEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string LanguageRus {
            get {
                return ResourceManager.GetString("LanguageRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application language.
        /// </summary>
        internal static string LanguagesApp {
            get {
                return ResourceManager.GetString("LanguagesApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukraine.
        /// </summary>
        internal static string LanguageUkr {
            get {
                return ResourceManager.GetString("LanguageUkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string messageError {
            get {
                return ResourceManager.GetString("messageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to exit this App?.
        /// </summary>
        internal static string messageExit {
            get {
                return ResourceManager.GetString("messageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string messageOk {
            get {
                return ResourceManager.GetString("messageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit App?.
        /// </summary>
        internal static string messageTitleExit {
            get {
                return ResourceManager.GetString("messageTitleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string messageСancel {
            get {
                return ResourceManager.GetString("messageСancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other (military fee), UAH.
        /// </summary>
        internal static string MilitaryTAX {
            get {
                return ResourceManager.GetString("MilitaryTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application on other platforms.
        /// </summary>
        internal static string OSAbout {
            get {
                return ResourceManager.GetString("OSAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Salary Calculator Ukraine in Google Play.
        /// </summary>
        internal static string OSAndroid {
            get {
                return ResourceManager.GetString("OSAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Salary Calculator Ukraine in Microsoft Store.
        /// </summary>
        internal static string OSMicrosoft {
            get {
                return ResourceManager.GetString("OSMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application does not collect or store any user information..
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy.
        /// </summary>
        internal static string PrivacyApp {
            get {
                return ResourceManager.GetString("PrivacyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate the app.
        /// </summary>
        internal static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsApp {
            get {
                return ResourceManager.GetString("SettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single social contribution, UAH.
        /// </summary>
        internal static string SSC {
            get {
                return ResourceManager.GetString("SSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the application theme.
        /// </summary>
        internal static string ThemesApp {
            get {
                return ResourceManager.GetString("ThemesApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        internal static string ThemesDarkName {
            get {
                return ResourceManager.GetString("ThemesDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string ThemesLightName {
            get {
                return ResourceManager.GetString("ThemesLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string ThemesOSName {
            get {
                return ResourceManager.GetString("ThemesOSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In development!.
        /// </summary>
        internal static string TitleDevelopment {
            get {
                return ResourceManager.GetString("TitleDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Salary Calculator Ukraine.
        /// </summary>
        internal static string TitleSalaryPage {
            get {
                return ResourceManager.GetString("TitleSalaryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something&apos;s wrong? Let me know .
        /// </summary>
        internal static string WrongLabel {
            get {
                return ResourceManager.GetString("WrongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In here.
        /// </summary>
        internal static string WrongLabelMail {
            get {
                return ResourceManager.GetString("WrongLabelMail", resourceCulture);
            }
        }
    }
}
